host: localhost
port: 6333
credentials:
  api_key: "your-api-key-here"
  user: "qdrant_user"
  password: "qdrant_password"

initial_data_file: "databases/data/vector_db_initial_data.json"
security:
  ssl_enabled: false
  ssl_cert_path: "/path/to/cert.pem"
  ssl_key_path: "/path/to/key.pem"

performance:
  max_concurrent_requests: 100
  batch_size: 100
  optimization_interval_sec: 3600