FROM python:3.12-slim-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["uvicorn", "sandbox_toolkit.infra.sandbox_base.api:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]