name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - BrunoScaglione
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug you encountered.
      placeholder: "Placeholder"
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected bahaviour
      description: Describe the expected behaviour
      placeholder: "Placeholder"
    validations:
      required: true

  - type: textarea
    id: bug-reproduction
    attributes:
      label: Bug reproduction
      description: Describe how to reproduce the bug
      placeholder: "E.g., 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant logs. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please cprovide any additional context that might help solving this issue.
      placeholder: "E.g., screenshots, OS, browser, etc."
    
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct. 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
