version: "3.9"

services:
  sandbox-orchestrator:
    build:
      context: ./sandbox_orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Orchestrator API port
    environment:
      ORCHESTRATOR_PORT: 8000
      QDRANT_HOST: qdrant_db
      QDRANT_PORT: 6333
      NEO4J_URI: neo4j://neo4j_db:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      - qdrant_db
      - neo4j_db
    networks:
      - sandbox_infra_network

  qdrant_db:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333" # HTTP port
      - "6334:6334" # GRPC port
    networks:
      - sandbox_infra_network
    volumes:
      - qdrant_data:/qdrant/storage

  neo4j_db:
    image: neo4j:5.14.0-community
    ports:
      - "7474:7474" # Browser interface
      - "7687:7687" # Bolt port
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS_UNMANAGED__0: '["apoc-5.14", "graph-data-science-2.5"]'
      NEO4J_APOC_EXPORT_FILE_ENABLED: 'true'
      NEO4J_APOC_IMPORT_FILE_ENABLED: 'true'
      NEO4J_APOC_IMPORT_FILE_USE_NEO4J_CONFIG: 'true'
    volumes:
      - neo4j_data:/data
      - ./graph_db/plugins:/plugins
      - ./graph_db/import:/import
    networks:
      - sandbox_infra_network

volumes:
  qdrant_data:
  neo4j_data:

networks:
  sandbox_infra_network:
    name: sandbox_infra_network