FROM python:3.12-slim-bookworm

WORKDIR /app

COPY . .

RUN uv sync && mkdir -p /knowledge_files

CMD ["uvicorn", "sandbox_toolkit.infra.sandbox_base.api:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
