[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sandbox_base"
version = "0.1.0"
dependencies = [
    "fastapi",
    "pydantic",
    "httpx",
]
