name: Auto Assign PRs

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Auto-assign pull request
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/workflows/auto-assign-pr-config.yml'