name: Auto Assign issues and pull requests

on:
  issues:
    types: [labeled]
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.label.name == 'bug' && 'BrunoScaglione' || github.event.label.name == 'enhancement' && 'lbVictor' }}
          numOfAssignee: 1

      - name: Auto-assign pull request
        uses: kentaro-m/auto-assign-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: BrunoScaglione
          reviewers: lbVictor
          number-of-assignees: 1
          number-of-reviewers: 1
          configuration-path: '.github/auto-assign.yml'