name: CI

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4    

      - name: Set up Python
        run: uv python install || exit 1

      - name: Install dependencies
        run: uv sync || exit 1

      - name: Install ci packages
        run: |
          uv add ruff pytest coverage

      - name: Lint with ruff
        run: |
          ruff check -output-format=github > ci-reports/lint-report.txt || exit 1

      - name: Format with ruff
        run: |
          ruff format -output-format=github > ci-reports/format-report.txt || exit 1

      - name: Run tests & code coverage
        run: |
          coverage run -m pytest --junitxml=ci-reports/pytest-report.xml || exit 1
          coverage xml -o ci-reports/coverage.xml || exit 1

      - name: Upload lint report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: ci-reports/lint-report.txt

      - name: Upload format report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: format-report
          path: ci-reports/format-report.txt

      - name: Upload test report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ci-reports/pytest-report.xml

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ci-reports/coverage.xml