name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v4    

      - name: Set up Python
        run: uv python install || exit 1

      - name: Install dependencies
        run: uv sync || exit 1

      - name: Install ci packages
        run: |
          uv add ruff pytest coverage

      - name: Lint with ruff
        run: |
          ruff . --fix --output-format=github || exit 1

      - name: Run tests & code coverage
        run: |
          coverage run -m pytest --junitxml=pytest-report.xml || exit 1
          coverage report || exit 1
          coverage xml || exit 1

      - name: Upload test report to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: pytest-report.xml

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml