name: Deploy Documentation to GitHub Pages

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4    

    - name: Set up Python
      run: uv python install

    - name: Install MkDocs and Material theme
      run: |
        uv venv
        uv add mkdocs-material

    - name: Build and Deploy MkDocs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run mkdocs gh-deploy --force