name: Auto-Fix Tagged Issue with LLMOps Issue Resolver

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
        description: target issue
      repository_name:
        required: true
        type: string
        description: name of the repository
    secrets:
      LLMOPS_ISSUE_RESOLVER_APP_ID:
        required: true
      LLMOPS_ISSUE_RESOLVER_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github app token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.LLMOPS_ISSUE_RESOLVER_APP_ID }}
          private-key: ${{ secrets.LLMOPS_ISSUE_RESOLVER_APP_PRIVATE_KEY }}

      - name: Pull toy-issues-with-github-actions repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository_name }}
          token: ${{ steps.generate-token.outputs.token }} 

      - name: Install uv
        uses: astral-sh/setup-uv@v4    

      - name: Set up Python
        run: uv python install

      - name: Install LLMOps Issue Resolver
        run: |
          uv venv
          uv add llmops-issue-resolver --default-index https://test.pypi.org/simple/ --index https://pypi.org/simple/ --upgrade

      - name: Store issue in ./issues/<issue_number>/issue.md
        uses: eunjae-lee/issue-to-markdown@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          label: assigned-to-llmops-issue-resolver
          slug_as_folder_name: false
          dest: issues
          authors: |
            BrunoScaglione
            lbVictor

      - name: Run LLMOps Issue Resolver
        id: llmops-issue-resolving
        run: |
          uv run llmops-issue-resolver-cli resolve-issue
          COMMIT_MESSAGE=$(uv run llmops-issue-resolver-cli get-commit-message)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: Clean up issue files
        run: |
          rm -rf ./issues

      - name: Stash changes, create patch branch, commit the changes to it, push & make a PR
        uses: peter-evans/create-pull-request@v7
        env:
          REPOSITORY_NAME: ${{ inputs.repository_name }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          COMMIT_MESSAGE: ${{ steps.llmops-issue-resolving.outputs.COMMIT_MESSAGE }}
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "[issue-resolving attempt] ${{ env.COMMIT_MESSAGE }}"
          author: github-actions\[bot] <ceo@freelunch.com>
          title: "[${{ env.REPOSITORY_NAME }}#${{ env.ISSUE_NUMBER }}] ${{ env.COMMIT_MESSAGE }}"
          body: Fixes /#${{ env.ISSUE_NUMBER }}. Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.    
          branch: patch/llmops-issue-resolver/${{ env.ISSUE_NUMBER }}
          sign-commits: true
          