name: 'Auto-Fix Tagged Issue with LLMOps Issue Resolver'

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
        description: target issue
      repository_name:
        required: true
        type: string
        description: name of the repository
    secrets:
      PAT_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  WHEEL_PATH: https://github.com/BrunoScaglione/llmops-issue-resolver/blob/main/llmops-issue-resolver/dist/llmops_issue_resolver-0.1.0-py3-none-any.whl

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Pull toy-issues-with-github-actions repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository_name }}
          token: ${{ secrets.PAT_TOKEN }} 

      - name: Install uv
        uses: astral-sh/setup-uv@v4    

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install LLMOps Issue Resolver
        run: |
          uv venv
          uv pip install $WHEEL_PATH

      - name: Store issue in ./issues/<issue_number>/issue.md
        uses: eunjae-lee/issue-to-markdown@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          label: assigned-to-llmops-issue-resolver
          slug_as_folder_name: false
          dest: issues

      - name: run LLMOps Issue Resolver
        run: |
          uv run llmops-issue-resolver-cli resolve_issue
          export COMMIT_MESSAGE = $(uv run llmops-issue-resolver-cli get_commit_message)

      - name: Stash changes, create patch branch, commit the changes to it, push & make a PR
        uses: peter-evans/create-pull-request@v7
        env:
          REPOSITORY_NAME: ${{ inputs.repository_name }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
        with:
          token: ${{ secrets.PAT_TOKEN }}   
          commit-message: '[issue-resolving attempt] $COMMIT_MESSAGE'
          author: LLMOps Issue Resolver <41898282+github-actions[bot]@users.noreply.github.com>
          title: '[BrunoScaglione/$REPOSITORY_NAME#$ISSUE_NUMBER] $COMMIT_MESSAGE'