name: 'Auto-Fix Tagged Issue with LLMOps Issue Resolver'

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
        description: 'Target issue'
      repository_name:
        required: true
        type: string
        description: 'Name of the repository'
    secrets:
      PAT_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-fix:
    if: github.event_name == 'workflow_call' 
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull llmops-issue-resolver repo'
        uses: 'actions/checkout@v4'
        with:
          repository: '$GH_REPO'
          token: '$PAT_TOKEN'

      - name: 'Install uv'
        uses: astral-sh/setup-uv@v4

      - name: 'Install Python'
        uses: 'actions/setup-python@v5'
        with:
          python-version: "3.12"

      - name: 'Install LLMOps Issue Resolver'
        run: |
          uv init
          uv add llmops-issue-resolver

      - name: 'Store issue body in ./issues/<issue_number>/issue.md'
        uses: 'eunjae-lee/issue-to-markdown@v1'
        with:
          token: ${{ secrets.PAT_TOKEN }}
          label: 'assigned-to-llmops-issue-resolver'
          slug_as_folder_name: false
          dest: 'issues'

      - name: 'Run LLMOps Issue Resolver'
        run: |
          uv run llmops-issue-resolver-cli resolve_issue
          export COMMIT_MESSAGE = $(uv run llmops-issue-resolver-cli get_commit_message)

      - name: 'Stash changes, create patch branch, commit the changes to it, push & make a PR'
        uses: 'peter-evans/create-pull-request@v7'
        with:
          token: '$PAT_TOKEN'
          commit-message: '[issue-resolving attempt] $COMMIT_MESSAGE'
          author: 'LLMOps Issue Resolver <41898282+github-actions[bot]@users.noreply.github.com>'
          title: '[BrunoScaglione/${{inputs.repository_name}}#${{inputs.issue_number}}] $COMMIT_MESSAGE'