name: Publish package to PyPi

on:
  push:
    branches:
      - release
    tags:
      - 'version=*.*.*'
  
jobs:
  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/llmops-issue-resolver

    name: Publish distribution
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1