on: push
  branches:
    - release

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install uv
        uses: astral-sh/setup-uv@v4    

    - name: Set up Python
      run: uv python install

    - name: Build package
      run: uv build

    - name: Build package
      run: uv build

    - name: push build to github
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish:
    name: Publish distribution
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: build
    
    environment:
      name: pypi
      url: https://pypi.org/p/llmops-issue-resolver

   steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish distribution to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: testpypi
      url: https://test.pypi.org/p/llmops-issue-resolver

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/


    
